sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

production:
  <<: *postgres
  database: beer30
