# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bff4092a79591ed2e89da9893593c37cf454c88de3aa6333e73ff2dd329d9f02bedc1e144acef4c527856392a3338f76e9bc9ccc40290ab4b013f1d80fa4a98

test:
  secret_key_base: b1dec1c6c5d44cce32d367b81d836bc7bed33a79b446fafea6cf2b7cb500e57314eef6fa722ce3701bd1be27c4f70e724275c22f276842c707bdfe69f3da41d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
